{{- if .Values.overlay.enabled -}}
apiVersion: aws.liferay.com/v1alpha1
kind: LiferayOverlay
metadata:
    annotations:
        argocd.argoproj.io/sync-options: ServerSideApply=true
        argocd.argoproj.io/sync-wave: "-20"
    name: {{ .Release.Name }}
    namespace: {{ .Release.Namespace }}
spec:
    commonTags:
        ProjectId: {{ .Values.projectId }}
    forceDestroy: {{ .Values.forceDestroy }}
    orphanOnDelete: {{ .Values.orphanOnDelete }}
    projectId: {{ .Values.projectId }}
    region: {{ .Values.region }}
{{- end -}}
