#!/bin/bash
# Bundles the modular KCL source into a single self-contained
# dist/pipeline.k that crossplane-function-kcl consumes inline via
# helm Files.Get.
#
# Splitting this from model generation keeps the default workflow fast and
# offline: model generation hits docker and kcl-openapi and only runs when
# the CRD surface changes (via generate-models).
set -e

function main {
    local compositions_directory
    compositions_directory="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
    local dist_directory="${compositions_directory}/dist"
    local models_directory="${compositions_directory}/models"

    mkdir -p "${dist_directory}"

    if [ ! -d "${models_directory}" ] || [ -z "$(ls -A "${models_directory}" 2>/dev/null)" ]
    then
        echo "error: \"${models_directory}\" does not exist or is empty. Run \"make generate-models\" first." >&2
        exit 1
    fi

    echo ""
    echo "Bundling \"${dist_directory}/pipeline.k\"."

    COMPOSITIONS_DIR="${compositions_directory}" DIST_DIR="${dist_directory}" MODELS_DIR="${models_directory}" python3 - <<'PY_EOF'
import os
import re

compositions_dir = os.environ["COMPOSITIONS_DIR"]
dist_dir = os.environ["DIST_DIR"]
models_dir = os.environ["MODELS_DIR"]


def strip_imports(s):
    return re.sub(r'(?m)^import .*', '', s)


# 1. Merge model schemas (dedup by schema name; shared types like ObjectMeta
#    get redefined per-CRD and would collide otherwise).
merged_models = ""
for root, _, files in os.walk(models_dir):
    for f in sorted(files):
        if not f.endswith('.k'):
            continue
        with open(os.path.join(root, f)) as fh:
            c = fh.read()
        # Strip the generated module-level docstring (starts at the first
        # triple-quote in the file). Each generator variant worded it
        # differently, so match on 'generated by' rather than the prefix.
        c = re.sub(r'\A"""[^"]*?generated by[^"]*?"""\n?', '', c, flags=re.DOTALL)
        # Strip per-schema raw docstrings (r"""...""") which are large and
        # irrelevant at crossplane runtime. Non-greedy match; raw docstrings
        # do not contain embedded triple-quotes in kcl-openapi output.
        c = re.sub(r'[ \t]*r"""[\s\S]*?"""\n?', '', c)
        merged_models += strip_imports(c) + "\n"

deduped = []
seen = set()
skip = False
for line in merged_models.split('\n'):
    m = re.match(r'^schema ([a-zA-Z0-9_]+):', line)
    if m:
        if m.group(1) in seen:
            skip = True
        else:
            skip = False
            seen.add(m.group(1))
    if not skip:
        deduped.append(line)

# 2. Stitch the bundle: shared imports, inlined models, shared context, and
#    each layer scoped inside a `<layer>_layer` schema so its private
#    helpers do not collide across layers.
layers = [
    "backup",
    "elasticsearch",
    "init",
    "k8s_resources",
    "managed_service_details",
    "overlay",
    "security",
    "sql",
    "storage",
]
shared_imports = [
    "import crypto",
    "import json",
    "import k8s.api.batch.v1 as k8s_batch",
    "import k8s.api.core.v1 as k8s_core",
    "import k8s.api.rbac.v1 as k8s_rbac",
    "import k8s.apimachinery.pkg.apis.meta.v1 as v1",
    "import yaml",
]
shared_aliases = {"crypto", "json", "k8s_batch", "k8s_core", "k8s_rbac", "v1", "yaml"}

pipeline = "\n".join(shared_imports) + "\n\n# --- MODELS ---\n" + "\n".join(deduped) + "\n\n"

with open(os.path.join(compositions_dir, "context_variables.k")) as fh:
    pipeline += "# --- CONTEXT ---\n" + strip_imports(fh.read()) + "\n\n"

for layer in layers:
    with open(os.path.join(compositions_dir, f"{layer}.k")) as fh:
        content = fh.read()
    aliases = re.findall(r'(?m)^import .* as ([a-zA-Z0-9_]+)', content)
    content = strip_imports(content)
    for alias in set(aliases):
        if alias in shared_aliases or alias == "cv":
            continue
        # Drop the alias prefix so bare schema names resolve against the
        # inlined models above. Only match when followed by an uppercase
        # letter so string literals like
        # "kubernetes.m.crossplane.io/v1alpha1" stay intact.
        content = re.sub(r'\b' + re.escape(alias) + r'\.(?=[A-Z])', '', content)
    # cv.xxx references become bare identifiers inlined into the layer scope
    # (context_variables.k is inlined above). cv. only appears on non-string
    # accesses in source files, so this is safe.
    content = re.sub(r'\bcv\.', '', content)
    # Inside the layer schema, KCL treats top-level `items = {...}` as a
    # local variable unless typed. Promote it to a typed attribute so callers
    # can read `_layer.items`.
    content = re.sub(r'(?m)^(\s*)items = ', r'\1items: {str:any} = ', content)
    indented = "\n".join("    " + ln if ln.strip() else ln for ln in content.split("\n"))
    pipeline += (
        f"schema {layer}_layer:\n{indented}\n\n"
        f"_{layer} = {layer}_layer {{}}\n"
        f"items_{layer} = _{layer}.items\n\n"
    )

pipeline += (
    "_layer_items = lambda layer {\n"
    "    _items = []\n"
    "    if typeof(layer) == \"list\":\n"
    "        _items = layer\n"
    "    elif layer and \"items\" in layer:\n"
    "        _items = layer.items\n"
    "    _items\n"
    "}\n"
    "items = {\"items\": [item for layer in ["
    + ",".join(f"items_{l}" for l in layers)
    + "] for item in _layer_items(layer)]}\n"
)

# Collapse runs of blank lines to shrink the bundle.
pipeline = re.sub(r'\n{3,}', '\n\n', pipeline)

with open(os.path.join(dist_dir, "pipeline.k"), "w") as fh:
    fh.write(pipeline)

kcl_mod = os.path.join(dist_dir, "kcl.mod")
if not os.path.exists(kcl_mod):
    with open(kcl_mod, "w") as fh:
        fh.write(
            '[package]\n'
            'name = "liferay-gcp-compositions"\n'
            'edition = "v0.12.3"\n'
            'version = "0.0.1"\n\n'
            '[dependencies]\n'
            'k8s = "1.32.4"\n'
        )
PY_EOF

    echo ""
    echo "Done. Bundle written to \"${dist_directory}/pipeline.k\"."
}

main
