{
 "title": "Kubernetes Workloads",
 "tags": [
  "Kubernetes",
  "Liferay",
  "Workloads"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "environment",
    "label": "Environment",
    "query": {
     "query": "label_values(kube_namespace_labels{label_liferay_com_observable=\"true\"},${NS_LABEL})"
    }
   }
  ]
 },
 "panels": [
  { "type": "text", "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 }, "options": { "content": "${HEADER_HTML}" } },
  {
   "title": "Liferay Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Service: Memory",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum by (pod) (\n  avg_over_time(container_memory_working_set_bytes{namespace=\"$environment\", pod=~\"liferay-.*\", container!=\"cloud-sql-proxy\"}[$__rate_interval])\n)",
       "legendFormat": "Usage | {{pod}}"
      },
      {
       "expr": "avg(\n  sum by (pod) (\n    avg_over_time(kube_pod_container_resource_requests{resource=\"memory\", ${NS_LABEL}=\"$environment\", pod=~\"liferay-.*\", container!=\"cloud-sql-proxy\"}[$__rate_interval])\n  )\n)",
       "legendFormat": "Requests"
      },
      {
       "expr": "avg(\n  sum by (pod) (\n    avg_over_time(kube_pod_container_resource_limits{resource=\"memory\", ${NS_LABEL}=\"$environment\", pod=~\"liferay-.*\", container!=\"cloud-sql-proxy\"}[$__rate_interval])\n  )\n)",
       "legendFormat": "Limits"
      }
     ]
    },
    {
     "title": "Service: CPU",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"$environment\", pod=~\"liferay-.*\", container!=\"cloud-sql-proxy\"}[$__rate_interval]))",
       "legendFormat": "Usage | {{ pod }}"
      },
      {
       "expr": "avg(\n  sum by (pod) (\n    avg_over_time(kube_pod_container_resource_requests{resource=\"cpu\", ${NS_LABEL}=\"$environment\", pod=~\"liferay-.*\", container!=\"cloud-sql-proxy\"}[$__rate_interval])\n  )\n)",
       "legendFormat": "Request"
      },
      {
       "expr": "avg(\n  sum by (pod) (avg_over_time(\n    kube_pod_container_resource_limits{resource=\"cpu\", ${NS_LABEL}=\"$environment\", pod=~\"liferay-.*\", container!=\"cloud-sql-proxy\"}[$__rate_interval])\n  )\n)",
       "legendFormat": "Limits"
      }
     ]
    },
    {
     "title": "Service: Restarts",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (pod)(increase(kube_pod_container_status_restarts_total{${NS_LABEL}=\"$environment\", pod=~\"liferay-.*\", container!=\"cloud-sql-proxy\"}[${__interval}]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "JVM Memory: By Area",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum by (pod, area) (avg_over_time({\"__name__\"=\"jvm_memory_used_bytes\", \"namespace\"=\"$environment\", \"pod\"=~\"liferay-.*\"}[$__rate_interval]))",
       "legendFormat": "{{pod}} | {{area}}"
      }
     ]
    },
    {
     "title": "JVM Threads: State",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 13 },
     "targets": [
      {
       "expr": "sum by (pod, state) (avg_over_time({\"__name__\"=\"jvm_threads_state\", \"namespace\"=\"$environment\", \"pod\"=~\"liferay-.*\"}[$__rate_interval])) > 0",
       "legendFormat": "{{pod}} | {{state}}"
      }
     ]
    },
    {
     "title": "JVM GC: Occupancy Rate (%)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum by (pod, gc) (rate({\"__name__\"=\"jvm_gc_collection_seconds_sum\", \"namespace\"=\"$environment\", \"pod\"=~\"liferay-.*\"}[$__rate_interval]))",
       "legendFormat": "{{pod}} | {{gc}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Search Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Service: Memory",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum by (pod) (\n  avg_over_time(container_memory_working_set_bytes{namespace=~\"$environment(-elasticsearch)?\", container=~\"elasticsearch|opensearch\"}[$__rate_interval])\n)",
       "legendFormat": "Usage | {{pod}}"
      },
      {
       "expr": "avg(\n  sum by (pod) (\n    avg_over_time(kube_pod_container_resource_requests{resource=\"memory\", ${NS_LABEL}=~\"$environment(-elasticsearch)?\", container=~\"elasticsearch|opensearch\"}[$__rate_interval])\n  )\n)",
       "legendFormat": "Requests"
      },
      {
       "expr": "avg(\n  sum by (pod) (\n    avg_over_time(kube_pod_container_resource_limits{resource=\"memory\", ${NS_LABEL}=~\"$environment(-elasticsearch)?\", container=~\"elasticsearch|opensearch\"}[$__rate_interval])\n  )\n)",
       "legendFormat": "Limits"
      }
     ]
    },
    {
     "title": "Service: CPU",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=~\"$environment(-elasticsearch)?\", container=~\"elasticsearch|opensearch\"}[$__rate_interval]))",
       "legendFormat": "Usage | {{ pod }}"
      },
      {
       "expr": "avg(\n  sum by (pod) (\n    avg_over_time(kube_pod_container_resource_requests{resource=\"cpu\", ${NS_LABEL}=~\"$environment(-elasticsearch)?\", container=~\"elasticsearch|opensearch\"}[$__rate_interval])\n  )\n)",
       "legendFormat": "Request"
      },
      {
       "expr": "avg(\n  sum by (pod) (avg_over_time(\n    kube_pod_container_resource_limits{resource=\"cpu\", ${NS_LABEL}=~\"$environment(-elasticsearch)?\", container=~\"elasticsearch|opensearch\"}[$__rate_interval])\n  )\n)",
       "legendFormat": "Limits"
      }
     ]
    },
    {
     "title": "Service: Restarts",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (pod)(increase(kube_pod_container_status_restarts_total{${NS_LABEL}=~\"$environment(-elasticsearch)?\", container=~\"elasticsearch|opensearch\"}[${__interval}]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}