{{- define "crossplane-runtime-configs.containerSecurityContext" -}}
securityContext:
    allowPrivilegeEscalation: false
    capabilities:
        drop:
            -   ALL
    privileged: false
    readOnlyRootFilesystem: true
{{- end -}}

{{- define "crossplane-runtime-configs.podSecurityContext" -}}
securityContext:
    fsGroup: 2000
    runAsGroup: 2000
    runAsNonRoot: true
    runAsUser: 2000
    seccompProfile:
        type: RuntimeDefault
{{- end -}}

{{- /*
kcl.step-source: build the source for one function-kcl pipeline step
from modular on-disk .k files.

Args (dict):
  root    -- the root template context (so Files.Get works)
  layer   -- layer name, e.g. "security" (reads compositions/<layer>.k)
  models  -- list of model file paths (relative to chart root) needed by the layer
  aliases -- list of import aliases the layer uses (e.g. ["sa", "kubernetes"])

What it does (replaces the Python bundler):
  1. Emits shared KCL imports (crypto, k8s.api.*, v1).
  2. Inlines each requested model file with its generator docstring,
     per-schema raw docstrings, and import lines stripped.
  3. Inlines context_variables.k (imports stripped; crypto is already
     imported above).
  4. Inlines the layer body (its own `import context_variables as cv`,
     `import models.*`, and other `import ... as X` lines stripped;
     `cv.` and `X.` prefixes rewritten to bare so the references
     resolve against the inlined schemas above).

The result is a single flat KCL source that arrives at function-kcl
without any wrapper schema, without any 4-space content indent that
could leak into triple-quoted string literals (today's heredoc bug
class is structurally impossible here -- YAML block-scalar `|`
normalizes Helm's indent).
*/ -}}
{{- define "kcl.step-source" -}}
{{- $root := .root -}}
{{- $layer := .layer -}}
{{- $models := .models | default (list) -}}
{{- $aliases := .aliases | default (list) -}}
import crypto
import k8s.api.batch.v1 as k8s_batch
import k8s.api.core.v1 as k8s_core
import k8s.api.rbac.v1 as k8s_rbac
import k8s.apimachinery.pkg.apis.meta.v1 as v1
{{ range $models }}
{{- $m := $root.Files.Get . -}}
{{- $m = regexReplaceAll "(?s)\\A\"\"\"[^\"]*?generated by[^\"]*?\"\"\"\\n?" $m "" -}}
{{- $m = regexReplaceAll "(?s)[ \\t]*r\"\"\".*?\"\"\"\\n?" $m "" -}}
{{- $m = regexReplaceAll "(?m)^import .*$" $m "" -}}
{{ $m }}
{{- end }}
{{- $ctx := $root.Files.Get "compositions/context_variables.k" -}}
{{- $ctx = regexReplaceAll "(?m)^import .*$" $ctx "" }}
{{ $ctx }}
{{- $body := $root.Files.Get (printf "compositions/%s.k" $layer) -}}
{{- $body = regexReplaceAll "(?m)^import .*$" $body "" -}}
{{- $body = regexReplaceAll "\\bcv\\." $body "" -}}
{{- range $aliases -}}
{{- $body = regexReplaceAll (printf "\\b%s\\.([A-Z])" .) $body "${1}" -}}
{{- end }}
{{ $body }}
{{- end -}}
