apiVersion: pkg.crossplane.io/v1
kind: Function
metadata:
    annotations:
        argocd.argoproj.io/sync-wave: "-80"
    name: function-kcl
spec:
    package: xpkg.upbound.io/crossplane-contrib/function-kcl:v0.10.1
---
apiVersion: pkg.crossplane.io/v1
kind: Function
metadata:
    annotations:
        argocd.argoproj.io/sync-wave: "-80"
    name: function-go-templating
spec:
    package: xpkg.upbound.io/crossplane-contrib/function-go-templating:v0.4.0
---
apiVersion: pkg.crossplane.io/v1
kind: Function
metadata:
    annotations:
        argocd.argoproj.io/sync-wave: "-80"
    name: function-auto-ready
spec:
    package: xpkg.upbound.io/crossplane-contrib/function-auto-ready:v0.2.1