{{- if .Values.marketplace.enabled }}
apiVersion: licensing.liferay.com/v1alpha1
kind: LiferayEnvironment
metadata:
    labels:
        app: {{ include "liferay.name" . }}
        {{- include "liferay.labels" . | nindent 8 }}
    name: {{ include "liferay.name" . }}
    namespace: {{ include "liferay.namespace" . }}
spec:
    {{- if .Values.marketplace.enabled }}
    marketplaceVolume:
    {{ .Values.marketplace | toYaml | nindent 8 }}
    {{- end }}
    workloadRef:
        name: {{ include "liferay.name" . }}
{{- end }}