{{- if .Values.marketplace.enabled }}
apiVersion: licensing.liferay.com/v1alpha1
kind: LiferayEnvironment
metadata:
    labels:
        app: {{ include "liferay.name" . }}
        {{- include "liferay.labels" . | nindent 8 }}
    name: {{ include "liferay.name" . }}
    namespace: {{ include "liferay.namespace" . }}
spec:
    marketplaceVolume:
        claimName: {{ .Values.marketplace.claimName | default (printf "%s-marketplace" (include "liferay.name" .)) }}
        size: {{ .Values.marketplace.size | quote }}
        storageClassName: {{ required "A ReadWriteMany storage class is required when marketplace.enabled is true. Set marketplace.storageClassName." .Values.marketplace.storageClassName | quote }}
    workloadRef:
        name: {{ include "liferay.name" . }}
{{- end }}
