{{- if and .Values.licensing.enabled .Values.licensing.onlineActivationWorkflow.enabled -}}
{{- $onlineActivationWorkflow := .Values.licensing.onlineActivationWorkflow -}}
{{- $image := printf "%s:%s" $onlineActivationWorkflow.image.repository (toString $onlineActivationWorkflow.image.tag) -}}
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
    labels:
        {{- include "liferay.labels" . | nindent 8 }}
    name: online-activation-workflow-template
    namespace: {{ include "liferay.namespace" . }}
spec:
    archiveLogs: false
    arguments:
        parameters:
            -   description:
                    The activation code issued for this environment.
                name: activation-code
    entrypoint: main
    podGC:
        strategy: OnWorkflowSuccess
    securityContext:
        runAsNonRoot: true
        runAsUser: 8737
        seccompProfile:
            type: RuntimeDefault
    serviceAccountName: {{ $onlineActivationWorkflow.serviceAccountName }}
    templates:
        -   name: main
            steps:
                -   -   name: find-environment
                        template: find-environment
                -   -   arguments:
                            parameters:
                                -   name: liferay-environment-name
                                    value: "{{ "{{" }}steps.find-environment.outputs.parameters.liferay-environment-name}}"
                        name: write-secret
                        template: write-secret
                -   -   arguments:
                            parameters:
                                -   name: liferay-environment-name
                                    value: "{{ "{{" }}steps.find-environment.outputs.parameters.liferay-environment-name}}"
                        name: request-reconcile
                        template: request-reconcile
                -   -   arguments:
                            parameters:
                                -   name: liferay-environment-name
                                    value: "{{ "{{" }}steps.find-environment.outputs.parameters.liferay-environment-name}}"
                        name: wait
                        template: wait
        -   name: find-environment
            outputs:
                parameters:
                    -   name: liferay-environment-name
                        valueFrom:
                            path: /tmp/liferay-environment-name.txt
            script:
                command: [sh]
                env:
                    -   name: HOME
                        value: /tmp
                    -   name: LIFERAY_NAMESPACE
                        value: "{{ "{{" }}workflow.namespace}}"
                image: {{ $image | quote }}
                resources:
                    {{- $onlineActivationWorkflow.resources | toYaml | nindent 20 }}
                securityContext:
                    allowPrivilegeEscalation: false
                    capabilities:
                        drop:
                            -   ALL
                    runAsNonRoot: true
                    runAsUser: 8737
                    seccompProfile:
                        type: RuntimeDefault
                source: |-
                    {{- tpl (.Files.Get "scripts/online-activation-find-environment.sh") . | nindent 20 }}
        -   inputs:
                parameters:
                    -   name: liferay-environment-name
            name: request-reconcile
            script:
                command: [sh]
                env:
                    -   name: HOME
                        value: /tmp
                    -   name: LIFERAY_WORKFLOW_NAME
                        value: "{{ "{{" }}workflow.name}}"
                image: {{ $image | quote }}
                resources:
                    {{- $onlineActivationWorkflow.resources | toYaml | nindent 20 }}
                securityContext:
                    allowPrivilegeEscalation: false
                    capabilities:
                        drop:
                            -   ALL
                    runAsNonRoot: true
                    runAsUser: 8737
                    seccompProfile:
                        type: RuntimeDefault
                source: |-
                    {{- tpl (.Files.Get "scripts/online-activation-request-reconcile.sh") . | nindent 20 }}
        -   inputs:
                parameters:
                    -   name: liferay-environment-name
            name: wait
            script:
                command: [sh]
                env:
                    -   name: HOME
                        value: /tmp
                image: {{ $image | quote }}
                resources:
                    {{- $onlineActivationWorkflow.resources | toYaml | nindent 20 }}
                securityContext:
                    allowPrivilegeEscalation: false
                    capabilities:
                        drop:
                            -   ALL
                    runAsNonRoot: true
                    runAsUser: 8737
                    seccompProfile:
                        type: RuntimeDefault
                source: |-
                    {{- tpl (.Files.Get "scripts/online-activation-wait.sh") . | nindent 20 }}
        -   inputs:
                parameters:
                    -   name: liferay-environment-name
            name: write-secret
            script:
                command: [sh]
                env:
                    -   name: HOME
                        value: /tmp
                    -   name: LIFERAY_ACTIVATION_CODE
                        value: "{{ "{{" }}workflow.parameters.activation-code}}"
                image: {{ $image | quote }}
                resources:
                    {{- $onlineActivationWorkflow.resources | toYaml | nindent 20 }}
                securityContext:
                    allowPrivilegeEscalation: false
                    capabilities:
                        drop:
                            -   ALL
                    runAsNonRoot: true
                    runAsUser: 8737
                    seccompProfile:
                        type: RuntimeDefault
                source: |-
                    {{- tpl (.Files.Get "scripts/online-activation-write-secret.sh") . | nindent 20 }}
    ttlStrategy:
        secondsAfterCompletion: {{ $onlineActivationWorkflow.ttlSecondsAfterCompletion }}
{{- end -}}