{{- if .Values.marketplace.enabled -}}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
    annotations:
        argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
        argocd.argoproj.io/sync-wave: "-90"
    name: marketplace-registry-credentials
    namespace: argocd-system
spec:
    dataFrom:
        -   sourceRef:
                generatorRef:
                    apiVersion: generators.external-secrets.io/v1alpha1
                    kind: ECRAuthorizationToken
                    name: marketplace-registry
    refreshInterval: 8h
    target:
        name: marketplace-registry-credentials
        template:
            data:
                password: {{ `"{{ .password }}"` }}
                type: oci
                url: oci://709825985650.dkr.ecr.us-east-1.amazonaws.com
                username: {{ `"{{ .username }}"` }}
            metadata:
                labels:
                    argocd.argoproj.io/secret-type: repo-creds
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: ECRAuthorizationToken
metadata:
    annotations:
        argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
        argocd.argoproj.io/sync-wave: "-90"
    name: marketplace-registry
    namespace: argocd-system
spec:
    region: us-east-1
{{- end -}}