{{- if .Values.providers.enabled -}}
{{- $providers := list
    (dict "name" "provider-aws-backup" "runtimeConfigName" "aws-backup-config")
    (dict "name" "provider-aws-cloudwatchlogs" "runtimeConfigName" "aws-cloudwatchlogs-config")
    (dict "name" "provider-aws-ec2" "runtimeConfigName" "aws-ec2-config")
    (dict "name" "provider-aws-iam" "runtimeConfigName" "aws-iam-config")
    (dict "name" "provider-aws-kms" "runtimeConfigName" "aws-kms-config")
    (dict "name" "provider-aws-opensearch" "runtimeConfigName" "aws-opensearch-config")
    (dict "name" "provider-aws-rds" "runtimeConfigName" "aws-rds-config")
    (dict "name" "provider-aws-s3" "runtimeConfigName" "aws-s3-config")
    (dict "name" "provider-family-aws" "runtimeConfigName" "aws-family-config" "syncWave" "-85")
-}}
{{- range $provider := $providers }}
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
    annotations:
        argocd.argoproj.io/sync-options: ServerSideApply=true,SkipDryRunOnMissingResource=true
        argocd.argoproj.io/sync-wave: {{ $provider.syncWave | default "-80" | quote }}
    name: {{ $provider.name }}
spec:
    package: xpkg.upbound.io/upbound/{{ $provider.name }}:v2.3.0
    runtimeConfigRef:
        name: {{ $provider.runtimeConfigName }}
    skipDependencyResolution: true
{{- end }}
{{- end -}}