labels: {}
managementPolicies:
    -   "*"
overlay:
    bucketName: ""
    enabled: false
    encryption:
        kmsKeyName: ""
    forceDestroy: false
    region: ""
    storageClass: STANDARD
    versioning: true