{{- $liferayDefault := index .Values "liferay-default" | default dict -}}
{{- $overlay := $liferayDefault.overlay | default dict -}}
{{- if and $overlay $overlay.enabled }}
{{- $bucketName := include "liferay-aws.overlayBucketName" . -}}
apiVersion: v1
kind: PersistentVolume
metadata:
    name: {{ $bucketName }}
spec:
    accessModes:
        -   ReadWriteMany
    capacity:
        storage: 10Gi
    claimRef:
        name: {{ $bucketName }}
        namespace: {{ .Release.Namespace }}
    csi:
        driver: s3.csi.aws.com
        volumeAttributes:
            bucketName: {{ $bucketName }}
        volumeHandle: {{ $bucketName }}
    storageClassName: {{ $bucketName }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: {{ $bucketName }}
spec:
    accessModes:
        -   ReadWriteMany
    resources:
        requests:
            storage: 10Gi
    storageClassName: {{ $bucketName }}
{{- end }}
