resource "helm_release" "argo_workflows" {
	chart="argo-workflows"
	depends_on=[
		kubernetes_namespace.argocd,
	]
	name="argo-workflows"
	namespace=kubernetes_namespace.argo_workflows.metadata[0].name
	repository="https://argoproj.github.io/argo-helm"
	upgrade_install=true
	values=[
		yamlencode(
			{
				controller={
					artifactRepository={
						archiveLogs=false
						s3={
							bucket=local.argo_artifacts_bucket_name
							keyFormat="artifacts/{{workflow.namespace}}/{{workflow.name}}/{{pod.name}}"
							region=var.region
							useSDKCreds=true
						}
					}
					podAnnotations=local.karpenter_pod_annotations
					resources={
						limits={
							memory="512Mi"
						}
						requests={
							cpu="15m"
							memory="128Mi"
						}
					}
				}
				server={
					podAnnotations=local.karpenter_pod_annotations
					resources={
						limits={
							memory="256Mi"
						}
						requests={
							cpu="15m"
							memory="128Mi"
						}
					}
					serviceAccount={
						name=local.argo_workflows_server_service_account_name
					}
				}
			}),
	]
	version=var.argo_workflows_helm_chart_version
}
resource "kubernetes_namespace" "argo_workflows" {
	metadata {
		labels=local.common_labels
		name=var.argo_workflows_namespace
	}
}