concurrency:
    cancel-in-progress: true
    group: publish-preview-charts-${{github.ref_name}}
defaults:
    run:
        shell: bash
jobs:
    setup:
        if: github.repository == 'cloudnative-team/liferay-portal'
        outputs:
            version_suffix: ${{steps.vars.outputs.version_suffix}}
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout code
                uses: actions/checkout@v4
                with:
                    fetch-depth: 1
                    filter: blob:none
                    show-progress: false
            -   id: vars
                name: Compute version suffix
                run: |
                    set -o errexit
                    set -o nounset
                    set -o pipefail

                    function main {
                        local sanitized_branch

                        sanitized_branch=$(echo "${GITHUB_REF_NAME}" | sed 's|/|-|g')

                        local short_sha

                        short_sha=$(git rev-parse --short HEAD)

                        echo "version_suffix=-${sanitized_branch}-${short_sha}" >> ${GITHUB_OUTPUT}
                    }

                    main "${@}"
    publish-aws:
        needs:
            -   publish-default
            -   setup
        secrets:
            project_id: ${{secrets.GCP_PROJECT_ID_EXTERNAL_NONPRD}}
            workload_identity_provider: ${{secrets.GCP_WORKLOAD_IDENTITY_PROVIDER_EXTERNAL_NONPRD}}
        uses: ./.github/workflows/ci-reusable-publish-helm-chart-to-gar.yaml
        with:
            chart_name: liferay-aws
            path_prefix: ${{github.ref_name}}
            registry: ${{vars.HELM_CHART_REGISTRY_NONPRD}}
            version_suffix: ${{needs.setup.outputs.version_suffix}}
            working_directory: ./cloud/helm/aws
    publish-aws-infrastructure:
        needs: setup
        secrets:
            project_id: ${{secrets.GCP_PROJECT_ID_EXTERNAL_NONPRD}}
            workload_identity_provider: ${{secrets.GCP_WORKLOAD_IDENTITY_PROVIDER_EXTERNAL_NONPRD}}
        uses: ./.github/workflows/ci-reusable-publish-helm-chart-to-gar.yaml
        with:
            chart_name: liferay-aws-infrastructure
            path_prefix: ${{github.ref_name}}
            registry: ${{vars.HELM_CHART_REGISTRY_NONPRD}}
            version_suffix: ${{needs.setup.outputs.version_suffix}}
            working_directory: ./cloud/helm/aws-infrastructure
    publish-aws-infrastructure-provider:
        needs: setup
        secrets:
            project_id: ${{secrets.GCP_PROJECT_ID_EXTERNAL_NONPRD}}
            workload_identity_provider: ${{secrets.GCP_WORKLOAD_IDENTITY_PROVIDER_EXTERNAL_NONPRD}}
        uses: ./.github/workflows/ci-reusable-publish-helm-chart-to-gar.yaml
        with:
            chart_name: liferay-aws-infrastructure-provider
            path_prefix: ${{github.ref_name}}
            registry: ${{vars.HELM_CHART_REGISTRY_NONPRD}}
            version_suffix: ${{needs.setup.outputs.version_suffix}}
            working_directory: ./cloud/helm/aws-infrastructure-provider
    publish-default:
        needs: setup
        secrets:
            project_id: ${{secrets.GCP_PROJECT_ID_EXTERNAL_NONPRD}}
            workload_identity_provider: ${{secrets.GCP_WORKLOAD_IDENTITY_PROVIDER_EXTERNAL_NONPRD}}
        uses: ./.github/workflows/ci-reusable-publish-helm-chart-to-gar.yaml
        with:
            chart_name: liferay-default
            path_prefix: ${{github.ref_name}}
            registry: ${{vars.HELM_CHART_REGISTRY_NONPRD}}
            version_suffix: ${{needs.setup.outputs.version_suffix}}
            working_directory: ./cloud/helm/default
    publish-gcp:
        needs:
            -   publish-default
            -   setup
        secrets:
            project_id: ${{secrets.GCP_PROJECT_ID_EXTERNAL_NONPRD}}
            workload_identity_provider: ${{secrets.GCP_WORKLOAD_IDENTITY_PROVIDER_EXTERNAL_NONPRD}}
        uses: ./.github/workflows/ci-reusable-publish-helm-chart-to-gar.yaml
        with:
            chart_name: liferay-gcp
            path_prefix: ${{github.ref_name}}
            registry: ${{vars.HELM_CHART_REGISTRY_NONPRD}}
            version_suffix: ${{needs.setup.outputs.version_suffix}}
            working_directory: ./cloud/helm/gcp
    publish-gcp-infrastructure:
        needs: setup
        secrets:
            project_id: ${{secrets.GCP_PROJECT_ID_EXTERNAL_NONPRD}}
            workload_identity_provider: ${{secrets.GCP_WORKLOAD_IDENTITY_PROVIDER_EXTERNAL_NONPRD}}
        uses: ./.github/workflows/ci-reusable-publish-helm-chart-to-gar.yaml
        with:
            chart_name: liferay-gcp-infrastructure
            path_prefix: ${{github.ref_name}}
            registry: ${{vars.HELM_CHART_REGISTRY_NONPRD}}
            version_suffix: ${{needs.setup.outputs.version_suffix}}
            working_directory: ./cloud/helm/gcp-infrastructure
    publish-gcp-infrastructure-provider:
        needs: setup
        secrets:
            project_id: ${{secrets.GCP_PROJECT_ID_EXTERNAL_NONPRD}}
            workload_identity_provider: ${{secrets.GCP_WORKLOAD_IDENTITY_PROVIDER_EXTERNAL_NONPRD}}
        uses: ./.github/workflows/ci-reusable-publish-helm-chart-to-gar.yaml
        with:
            chart_name: liferay-gcp-infrastructure-provider
            path_prefix: ${{github.ref_name}}
            registry: ${{vars.HELM_CHART_REGISTRY_NONPRD}}
            version_suffix: ${{needs.setup.outputs.version_suffix}}
            working_directory: ./cloud/helm/gcp-infrastructure-provider
on:
    push:
        branches:
            -   LCD-*
        paths:
            -   .github/workflows/ci-reusable-publish-cloud-helm-charts.yaml
            -   .github/workflows/ci-reusable-publish-helm-chart-to-gar.yaml
            -   cloud/helm/**
permissions:
    contents: read
    id-token: write