defaults:
    run:
        shell: bash
jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout code
                uses: actions/checkout@v4
                with:
                    fetch-depth: 1
                    filter: blob:none
                    show-progress: false
            -   name: Compute environment variables
                run: |
                    set -o errexit
                    set -o nounset
                    set -o pipefail

                    function main {
                        local chart_version

                        chart_version=$(yq .version Chart.yaml)

                        local registry="${{inputs.registry}}"

                        if [[ -n "${{inputs.path_prefix}}" ]]
                        then
                            registry="${registry}/${{inputs.path_prefix}}"
                        fi

                        local target_ref="${registry}/${{inputs.chart_name}}:${chart_version}${{inputs.version_suffix}}"

                        echo "Will push chart to ${target_ref}"

                        echo "CHART_VERSION=${chart_version}" >> ${GITHUB_ENV}
                        echo "DIST_DIR=${{runner.temp}}/${{inputs.chart_name}}/dist" >> ${GITHUB_ENV}
                        echo "TARGET_REF=${target_ref}" >> ${GITHUB_ENV}
                    }

                    main "${@}"
                working-directory: ${{inputs.working_directory}}
            -   id: auth
                name: Authenticate to Google Cloud
                uses: google-github-actions/auth@v3
                with:
                    project_id: ${{secrets.project_id}}
                    workload_identity_provider: ${{secrets.workload_identity_provider}}
            -   name: Install oras
                uses: oras-project/setup-oras@v1
            -   name: Log in to GAR
                run: |
                    set -o errexit
                    set -o nounset
                    set -o pipefail

                    function main {
                        echo "${{steps.auth.outputs.auth_token}}" \
                            | oras login \
                                --password-stdin \
                                --username oauth2accesstoken \
                                us-central1-docker.pkg.dev
                    }

                    main "${@}"
            -   name: Package Helm chart
                run: |
                    set -o errexit
                    set -o nounset
                    set -o pipefail

                    function main {
                        rm --force --recursive "${DIST_DIR}"

                        mkdir --parents "${DIST_DIR}"

                        helm dependency update

                        helm package . \
                            --destination "${DIST_DIR}" \
                            --version "${CHART_VERSION}"
                    }

                    main "${@}"
                working-directory: ${{inputs.working_directory}}
            -   name: Push to OCI with custom tag
                run: |
                    set -o errexit
                    set -o nounset
                    set -o pipefail

                    function main {
                        local config_file="helm-oci-config.json"
                        local tgz="${{inputs.chart_name}}-${CHART_VERSION}.tgz"

                        cd "${DIST_DIR}"

                        printf '{"name":"%s","version":"%s"}' \
                            "${{inputs.chart_name}}" \
                            "${CHART_VERSION}" \
                            > "${config_file}"

                        oras push \
                            "${TARGET_REF}" \
                            --config "${config_file}:application/vnd.cncf.helm.config.v1+json" \
                            "${tgz}:application/vnd.cncf.helm.chart.content.v1.tar+gzip"
                    }

                    main "${@}"
on:
    workflow_call:
        inputs:
            chart_name:
                required: true
                type: string
            path_prefix:
                default: ""
                required: false
                type: string
            registry:
                required: true
                type: string
            version_suffix:
                default: ""
                required: false
                type: string
            working_directory:
                required: true
                type: string
        secrets:
            project_id:
                required: true
            workload_identity_provider:
                required: true
permissions:
    contents: read
    id-token: write