defaults:
    run:
        shell: bash
jobs:
    test-cloud-helm-chart:
        if: ${{github.repository == 'cloudnative-team/liferay-portal'}}
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout code
                uses: actions/checkout@v4
            -   name: Install Helm
                uses: azure/setup-helm@v4
            -   name: Install helm-unittest plugin
                run: helm plugin install --verify=false --version 1.0.3 https://github.com/helm-unittest/helm-unittest
            -   name: Set up Kubeconform
                uses: bmuschko/setup-kubeconform@v1
                with:
                    kubeconform-version: 0.7.0
            -   name: Update chart dependencies
                run: helm dependency update --skip-refresh "cloud/helm/${{matrix.chart}}"
            -   name: Lint chart
                run: helm lint "cloud/helm/${{matrix.chart}}"
            -   name: Render and validate manifests
                run: |
                    set -o errexit
                    set -o nounset
                    set -o pipefail

                    function main {
                        helm template liferay "cloud/helm/${{matrix.chart}}" | \
                            kubeconform --strict --summary \
                                -schema-location default \
                                -schema-location 'https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/{{.Group}}/{{.ResourceKind}}_{{.ResourceAPIVersion}}.json' \
                                -skip ClusterProviderConfig,LiferayInfrastructure
                    }

                    main "${@}"
            -   name: Run unit tests
                run: |
                    set -o errexit
                    set -o nounset
                    set -o pipefail

                    function main {
                        local test_files

                        test_files=$(ls "cloud/helm/${{matrix.chart}}/tests/"*_test.yaml 2>/dev/null || echo "")

                        if [ "${test_files}" ]
                        then
                            mkdir --parents cloud/test-reports

                            helm unittest \
                                --output-file "cloud/test-reports/helm-unittest-${{matrix.chart}}.xml" \
                                --output-type JUnit \
                                "cloud/helm/${{matrix.chart}}"
                        fi
                    }

                    main "${@}"
        strategy:
            fail-fast: false
            matrix:
                chart:
                    -   aws
                    -   aws-infrastructure
                    -   aws-infrastructure-provider
                    -   aws-marketplace
                    -   default
                    -   gcp
                    -   gcp-infrastructure
                    -   gcp-infrastructure-provider
on:
    pull_request:
        paths:
            -   cloud/helm/**
    push:
        branches:
            -   master
        paths:
            -   cloud/**