defaults:
    run:
        shell: bash
jobs:
    test-cloud-helm-chart:
        if: ${{github.repository == 'cloudnative-team/liferay-portal'}}
        permissions:
            checks: write
            contents: read
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout code
                uses: actions/checkout@v4
            -   name: Install Helm
                uses: azure/setup-helm@v4
            -   name: Install helm-unittest plugin
                run: helm plugin install --verify=false --version 1.0.3 https://github.com/helm-unittest/helm-unittest
            -   name: Set up Kubeconform
                uses: bmuschko/setup-kubeconform@v1
                with:
                    kubeconform-version: 0.7.0
            -   name: Run Helm chart tests
                run: ./cloud/scripts/tests/run-helm-tests.sh "${{matrix.chart}}" cloud/test-reports
            -   name: Upload test reports
                if: ${{!cancelled()}}
                uses: actions/upload-artifact@v4
                with:
                    name: helm-test-reports-${{matrix.chart}}
                    path: cloud/test-reports/*.xml
            -   name: Publish test report
                if: ${{!cancelled()}}
                uses: dorny/test-reporter@v2
                with:
                    name: Helm tests (${{matrix.chart}})
                    path: cloud/test-reports/*.xml
                    reporter: java-junit
        strategy:
            fail-fast: false
            matrix:
                chart:
                    -   aws
                    -   aws-infrastructure
                    -   aws-infrastructure-provider
                    -   aws-marketplace
                    -   default
                    -   gcp
                    -   gcp-infrastructure
                    -   gcp-infrastructure-provider
on:
    pull_request:
        paths:
            -   .github/workflows/ci-test-cloud-helm-chart.yaml
            -   cloud/helm/**
            -   cloud/scripts/tests/**
    push:
        branches:
            -   master
        paths:
            -   cloud/**
